apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: confident-coral-nodejs
  janus-idp.io/tekton: confident-coral-nodejs
  backstage.io/kubernetes-id: confident-coral-nodejs
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: confident-coral-nodejs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
