apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: confident-coral-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: confident-coral-nodejs 
  name: confident-coral-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: confident-coral-nodejs 
